package com.sadraii.remotepaycomparison.ui.theme

import androidx.compose.ui.graphics.Color

//val Purple200 = Color(0xFFBB86FC)
//val Purple500 = Color(0xFF6200EE)
//val Purple700 = Color(0xFF3700B3)
//val Teal200 = Color(0xFF03DAC5)
//
//val PrimaryColor = Color(0xFF09181D)
//val PrimaryLightColor = Color(0xFF303E44)
//val PrimaryDarkColor = Color(0xFF000000)
//val SecondaryColor = Color(0xFF80CDE1)
//val SecondaryLightColor = Color(0xFFB3FFFF)
//val SecondaryDarkColor = Color(0xFF4D9CAF)
//val PrimaryTextColor = Color(0xFFAAB8BB)
//val SecondaryTextColor = Color(0xFF0E091D)

val md_theme_light_primary = Color(0xFF00677f)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFb1ebff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f28)
val md_theme_light_secondary = Color(0xFF00687b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFa6edff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f26)
val md_theme_light_tertiary = Color(0xFF00687a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFa6edff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f26)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfe)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfe)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdbe4e8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484b)
val md_theme_light_outline = Color(0xFF70787c)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f2)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF5bd5fa)
val md_theme_dark_onPrimary = Color(0xFF003543)
val md_theme_dark_primaryContainer = Color(0xFF004e61)
val md_theme_dark_onPrimaryContainer = Color(0xFFb1ebff)
val md_theme_dark_secondary = Color(0xFF54d6f3)
val md_theme_dark_onSecondary = Color(0xFF003641)
val md_theme_dark_secondaryContainer = Color(0xFF004e5d)
val md_theme_dark_onSecondaryContainer = Color(0xFFa6edff)
val md_theme_dark_tertiary = Color(0xFF55d7f3)
val md_theme_dark_onTertiary = Color(0xFF003641)
val md_theme_dark_tertiaryContainer = Color(0xFF004e5c)
val md_theme_dark_onTertiaryContainer = Color(0xFFa6edff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF40484b)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8cc)
val md_theme_dark_outline = Color(0xFF899296)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF09181d)
val error = Color(0xFFba1b1b)